import { writeFileSync } from "fs";
import { rExecutor } from "../r_bridge/executor.js";
import { logger } from "../utils/logger.js";

interface GenerateReportArgs {
  analysis_results: any;
  format?: "html" | "pdf";
  include_code?: boolean;
  output_path: string;
}

/**
 * Generate comprehensive Cochrane-style report
 */
export async function generateReportTool(args: unknown) {
  const {
    analysis_results,
    format = "html",
    include_code = false,
    output_path,
  } = args as GenerateReportArgs;

  logger.info(`Generating ${format.toUpperCase()} report: ${output_path}`);

  try {
    // Generate HTML report
    const htmlContent = generateHTMLReport(analysis_results, include_code);

    if (format === "html") {
      writeFileSync(output_path, htmlContent);

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(
              {
                success: true,
                message: "Report generated successfully",
                output_path,
                format: "HTML",
              },
              null,
              2
            ),
          },
        ],
      };
    } else {
      // For PDF, use R to convert HTML to PDF
      const rCode = `
library(rmarkdown)

html_content <- '${htmlContent.replace(/'/g, "\\'").replace(/\n/g, "\\n")}'
html_file <- tempfile(fileext = ".html")
writeLines(html_content, html_file)

# Convert to PDF (requires pandoc and LaTeX)
rmarkdown::pandoc_convert(
  html_file,
  to = "pdf",
  output = "${output_path}"
)

cat(toJSON(list(success = TRUE, output = "${output_path}"), auto_unbox = TRUE))
      `;

      await rExecutor.execute(rCode);

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(
              {
                success: true,
                message: "PDF report generated successfully",
                output_path,
                format: "PDF",
              },
              null,
              2
            ),
          },
        ],
      };
    }
  } catch (error) {
    logger.error("Report generation error:", error);
    throw error;
  }
}

/**
 * Generate HTML report content
 */
function generateHTMLReport(results: any, includeCode: boolean): string {
  const date = new Date().toISOString().split("T")[0];

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meta-Analysis Report</title>
    <style>
        body {
            font-family: 'Times New Roman', Times, serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }
        h1, h2, h3 {
            color: #2c3e50;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .summary-box {
            background-color: #f9f9f9;
            border-left: 4px solid #3498db;
            padding: 15px;
            margin: 20px 0;
        }
        .warning {
            background-color: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin: 20px 0;
        }
        .code-block {
            background-color: #f4f4f4;
            border: 1px solid #ddd;
            padding: 10px;
            font-family: 'Courier New', monospace;
            font-size: 12px;
            overflow-x: auto;
        }
    </style>
</head>
<body>
    <h1>Meta-Analysis Report</h1>
    <p><strong>Date:</strong> ${date}</p>
    <p><strong>Generated by:</strong> Cochrane Meta-Analysis MCP Server</p>

    <div class="summary-box">
        <h2>Summary</h2>
        <p><strong>Effect Measure:</strong> ${results.effect_measure}</p>
        <p><strong>Model:</strong> ${results.model === "random" ? "Random-effects" : "Fixed-effect"}</p>
        <p><strong>Number of Studies:</strong> ${results.n_studies}</p>
        <p><strong>Total Participants:</strong> ${results.n_participants}</p>
    </div>

    <h2>Pooled Effect Estimate</h2>
    <table>
        <tr>
            <th>Estimate</th>
            <th>95% CI Lower</th>
            <th>95% CI Upper</th>
            <th>P-value</th>
        </tr>
        <tr>
            <td>${results.pooled_effect.estimate.toFixed(3)}</td>
            <td>${results.pooled_effect.lower_ci.toFixed(3)}</td>
            <td>${results.pooled_effect.upper_ci.toFixed(3)}</td>
            <td>${results.pooled_effect.p_value ? results.pooled_effect.p_value.toFixed(4) : "N/A"}</td>
        </tr>
    </table>

    <h2>Heterogeneity Assessment</h2>
    <table>
        <tr>
            <th>Statistic</th>
            <th>Value</th>
            <th>Interpretation</th>
        </tr>
        <tr>
            <td>I² (%)</td>
            <td>${results.heterogeneity.I2.toFixed(1)}%</td>
            <td>${results.heterogeneity.I2 > 75 ? "Considerable" : results.heterogeneity.I2 > 50 ? "Substantial" : "Low to moderate"}</td>
        </tr>
        <tr>
            <td>Q statistic</td>
            <td>${results.heterogeneity.Q.toFixed(2)}</td>
            <td>df = ${results.heterogeneity.df}</td>
        </tr>
        <tr>
            <td>Q p-value</td>
            <td>${results.heterogeneity.p_value.toFixed(4)}</td>
            <td>${results.heterogeneity.p_value < 0.10 ? "Significant heterogeneity" : "No significant heterogeneity"}</td>
        </tr>
        <tr>
            <td>τ² (tau-squared)</td>
            <td>${results.heterogeneity.tau2.toFixed(3)}</td>
            <td>Between-study variance</td>
        </tr>
    </table>

    ${results.heterogeneity.I2 > 60 ? `
    <div class="warning">
        <strong>Note:</strong> Substantial heterogeneity detected (I² > 60%). Consider investigating sources of heterogeneity through subgroup analysis or meta-regression.
    </div>
    ` : ""}

    <h2>Individual Study Results</h2>
    <table>
        <tr>
            <th>Study</th>
            <th>Effect Size</th>
            <th>95% CI</th>
            <th>Weight (%)</th>
        </tr>
        ${results.study_effects.map((study: any) => `
        <tr>
            <td>${study.study_id}</td>
            <td>${study.effect_size.estimate.toFixed(3)}</td>
            <td>[${study.effect_size.lower_ci.toFixed(3)}, ${study.effect_size.upper_ci.toFixed(3)}]</td>
            <td>${study.effect_size.weight ? study.effect_size.weight.toFixed(1) : "N/A"}</td>
        </tr>
        `).join("")}
    </table>

    <h2>Interpretation</h2>
    <p>This meta-analysis included ${results.n_studies} studies with a total of ${results.n_participants} participants.
    The pooled ${results.effect_measure} was ${results.pooled_effect.estimate.toFixed(3)}
    (95% CI: ${results.pooled_effect.lower_ci.toFixed(3)} to ${results.pooled_effect.upper_ci.toFixed(3)})${results.pooled_effect.p_value ? `, p=${results.pooled_effect.p_value.toFixed(4)}` : ""}.</p>

    ${results.heterogeneity.I2 > 50 ? `
    <p>Substantial heterogeneity was observed (I² = ${results.heterogeneity.I2.toFixed(1)}%),
    indicating variability in treatment effects across studies. This suggests that the intervention effect may vary
    depending on study characteristics.</p>
    ` : `
    <p>Low to moderate heterogeneity was observed (I² = ${results.heterogeneity.I2.toFixed(1)}%),
    suggesting relatively consistent effects across studies.</p>
    `}

    <h2>Recommendations</h2>
    <ul>
        <li>Assess publication bias using funnel plot and statistical tests (Egger's test, trim-and-fill)</li>
        <li>Perform sensitivity analyses to test robustness of findings</li>
        <li>Consider subgroup analyses if sufficient studies are available</li>
        <li>Conduct GRADE assessment to evaluate certainty of evidence</li>
        <li>Assess risk of bias using Cochrane RoB 2 tool</li>
    </ul>

    ${includeCode ? `
    <h2>Statistical Methods</h2>
    <div class="code-block">
<pre>
Meta-analysis performed using R metafor package
Effect measure: ${results.effect_measure}
Model: ${results.model === "random" ? "Random-effects (REML)" : "Fixed-effect"}
Confidence level: 95%

Heterogeneity quantified using:
- I² statistic
- Cochran's Q test
- τ² (tau-squared)
</pre>
    </div>
    ` : ""}

    <footer>
        <p><em>Generated by Cochrane Meta-Analysis MCP Server v0.1.0</em></p>
        <p><em>This report follows Cochrane Handbook Chapter 10 guidelines</em></p>
    </footer>
</body>
</html>`;
}
